server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eladmin?useSSL=false&characterEncoding=utf-8
    username: eladmin
    password: 123456

mybatis:
  type-aliases-package: com.dmkj.ljadmin.dao

springdoc:
  swagger-ui:
    enabled: true

application:
  security:
    jwt:
      token-header: Authorization
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
